### ISSUE TITLE
Small issu in readme.md

### ISSUE THREAD

**Issue by dsiekiera** [davaxi/Sparkline#1]
In your "Documentation" you wrote:
`// Change fill color (Default value #e6f2fa)`
`$sparkline->setLineColorHex('#8b1c2b');`
`// or`
`$sparkline->setLineColorRGB(139, 28, 43);`

but must be:
`// Change fill color (Default value #e6f2fa)`
`$sparkline->setFillColorHex('#8b1c2b');`
`// or`
`$sparkline->setFillColorRGB(139, 28, 43);`

Thats all ;-)

Regards, Daniel

**Comment by davaxi** [comment]
Done :)
