### ISSUE TITLE
Decimal values not working

### ISSUE THREAD

**Issue by Modrx** [davaxi/Sparkline#16]
Hi,

1. When using decimal values it seems to be not working, ex:
0.222555715,0.220765615,0.22922179,0.23053631,0.23778608,0.23575197,0.239149585

2. How do I insert an array/variable with values inside $sparkline->setData(array($variable_values)):
ex:
$variable_values = "0.222555715,0.220765615,0.22922179,0.23053631,0.23778608,0.23575197,0.239149585";
$sparkline->setData(array($variable_values));
It's not working.

Thank you!

**Comment by davaxi** [comment]
Sparkline is not design for decimal values. You can multiply your values by 100 000 000 for to have same rendering.

**Comment by Modrx** [comment]
Can you please also tell me how to pass values for the following, it's not working for some reason:

```
$variable_values = "1,2,3,4,5,6,7";
$sparkline->setData(array($variable_values));
```

Thank you very much!

**Comment by Findus23** [comment]
@Modrx `array()` just converts your string to a list that contains your string. You have to pass a list of integers to sparkline, so you need to explode it and possible also convert those strings to integers (it has been a while since I last used PHP).
```php
<?php
$variable_values = "1,2,3,4,5,6,7";
var_dump(array($variable_values));
//    array(1) {
//      [0]=>
//      string(13) "1,2,3,4,5,6,7"
//    }
var_dump(explode(",", $variable_values));
//    array(7) {
//      [0]=>
//      string(1) "1"
//      [1]=>
//      string(1) "2"
//      [2]=>
//      string(1) "3"
//      [3]=>
//      string(1) "4"
//      [4]=>
//      string(1) "5"
//      [5]=>
//      string(1) "6"
//      [6]=>
//      string(1) "7"
//    }
var_dump(array_map("intval", explode(",", $variable_values)));
//    array(7) {
//      [0]=>
//      int(1)
//      [1]=>
//      int(2)
//      [2]=>
//      int(3)
//      [3]=>
//      int(4)
//      [4]=>
//      int(5)
//      [5]=>
//      int(6)
//      [6]=>
//      int(7)
//    }

**Comment by Modrx** [comment]
Thank you!!
