### ISSUE TITLE
Flat graph on larger numbers

### ISSUE THREAD

**Issue by Xuggy** [davaxi/Sparkline#17]
I'm attempting to graph the following numbers but find I can't get the graph to start at the origin:
   I think"setOriginValue" is meant to make the y axis begin at 37? It doesn't seem to work.

```
    $sparkline = new Davaxi\Sparkline();
    $sparkline->setBase(50);
    $sparkline->setOriginValue(37);
    $sparkline->setFormat('100x40');
    $sparkline->setData(array(37, 37, 40, 40, 40));
    $sparkline->display();
```

**Comment by Xuggy** [comment]
Noticed this issue is in pull request. Is anyone intending to fix it?

I suppose in the meantime one can remove the minimum array value from all numbers to drag the graph down to the origin (0) as a visual fix.

**Comment by davaxi** [comment]
I, sorry the Merge request #9 has been just checked and merged. I test your case and fix work.
