### ISSUE TITLE
PHP8.1 Deprecation - Implicit conversion from float to int loses precision

### ISSUE THREAD

**Issue by Findus23** [davaxi/Sparkline#19]
Just an early heads-up from beta2:

https://github.com/davaxi/Sparkline/blob/9117a5e4ee51d407adad2c11dc75e5be35b61ca5/src/Sparkline/Picture.php#L115

https://github.com/davaxi/Sparkline/blob/9117a5e4ee51d407adad2c11dc75e5be35b61ca5/src/Sparkline/Picture.php#L137-L144

 see https://wiki.php.net/rfc/implicit-float-int-deprecate

**Comment by davaxi** [comment]
I upgrade version for PHP8.1 compatibility in next week.

**Comment by davaxi** [comment]
After merged https://github.com/davaxi/Sparkline/pull/20 it's ok.
