### ISSUE TITLE
bug when generating big numbers

### ISSUE THREAD

**Issue by llabbasmkhll** [davaxi/Sparkline#22]
I wanted to create a bitcoin price mini chart with this package.
When i add an array with very big numbers it does not create appropriate chart
For example this code (series of numbers) :

```php
$prices = [
    10001,10400,10115,10056,10014,10033,10001,10008,10009,10007
];

$sparkline = new Davaxi\Sparkline();
$sparkline->setFormat('800x400');
$sparkline->setOriginValue(min($prices));
$sparkline->setData($prices);
$sparkline->save('./pic.png');
```
generates this image :
![pic](https://user-images.githubusercontent.com/86796762/150364361-fabfc66c-de42-486b-96ff-d93fe1175dd8.png)

**Comment by davaxi** [comment]
Hi, 

It's not a bug with large number. `Sparkline`, determine max value from original values of data In your case : `10400`.  And height of value is : from 0 to 10400. ButWhen you use :  
```php
<?php

// ... 
$sparkline->setOriginvalue(min($prices));
```
You redefine min value of chart to `10 001`, all values is replaced by `$OriginaValue - $originalValue` and values is replaced by diff value . BUT base of computing height is always `10 400` and height is from `10 001` to `10 400`. You are this return. 

For have expected result, you need to re-define base of computing. This code work : 
```php
$prices = [
    10001,10400,10115,10056,10014,10033,10001,10008,10009,10007
];

$sparkline = new Davaxi\Sparkline();
$sparkline->setFormat('800x400');
$sparkline->setOriginValue(min($prices));

$sparkline->setBase(max($prices) - min($prices));

$sparkline->setData($prices);
$sparkline->save('./pic.png');
````
![Capture d’écran 2022-03-11 à 13 52 43](https://user-images.githubusercontent.com/870169/157870106-052c3994-1d22-4104-ad1c-3d47efaaa927.png)
