### ISSUE TITLE
Lowest point

### ISSUE THREAD

**Issue by GuilVII** [davaxi/Sparkline#5]
Hi, first of all thanks a lot for your great work. I'm facing similar issue as above about the minimum low value. Let's say I have the following values: 8000,9000,8500,11000,10500,10200
Google charts would show the following graph:

![capture d ecran 2017-12-02 a 12 26 17](https://user-images.githubusercontent.com/34185715/33515077-71ab1ad6-d75e-11e7-8833-1ae5ee7ee7af.png)

However the minimum value of your graph being 0 by default, your sparkline graph will show:

![capture d ecran 2017-12-02 a 12 29 48](https://user-images.githubusercontent.com/34185715/33515078-74298220-d75e-11e7-9040-d159518070f4.png)

I know there is the setBase option for the max point but what about the lowest point? Any idea how could I easily tweak this? 

Thanks a lot

**Comment by davaxi** [comment]
Great idea. I work on new release twho integrate this issue.

**Comment by davaxi** [comment]
I create method `$sparkline->setOriginValue` in new release 1.0.6 for this issue :)

**Comment by Pfaufisch** [comment]
No matter which value I use with setOriginValue(), the output doesn't change for me. Is this still working as intended?
