### ISSUE TITLE
1.0.6 release broke Picture->applyPolygon

### ISSUE THREAD

**Issue by KyleFromOhio** [davaxi/Sparkline#6]
`PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Davaxi\Sparkline\Picture::applyPolygon() must be of the type array, null given, called in vendor/davaxi/sparkline/src/Sparkline.php on line 115 and defined in vendor/davaxi/sparkline/src/Sparkline/Picture.php:95`

`Stack trace:
\#0 vendor/davaxi/sparkline/src/Sparkline.php(115): Davaxi\Sparkline\Picture->applyPolygon(Array, NULL, 577)
\#1 vendor/davaxi/sparkline/src/Sparkline.php(201): Davaxi\Sparkline->generate()
\#2 cron/cron_create_chart.php(140): Davaxi\Sparkline->save(...)
\#3 {main}
  thrown in vendor/davaxi/sparkline/src/Sparkline/Picture.php on line 95`

Had to revert back to 1.0.5

**Comment by davaxi** [comment]
Thanks for this issue. Last release 1.0.7 fix this issue. Tell me if other problem appear.
